##---
# Source: olm/templates/02-alm-operator.rolebinding.yaml
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: alm-operator-binding
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: alm-operator-serviceaccount
  namespace: rhcc
