##---
# Source: olm/templates/14-alm-servicebroker.clusterservicebroker.yaml

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  finalizers:
  - kubernetes-incubator/service-catalog
  name: alm-service-broker
spec:
  authInfo:
    bearer:
      secretRef:
        name: almservicebroker-client
        namespace: rhcc
  relistBehavior: Duration
  relistDuration: 15m0s
  relistRequests: 0
  url: http://alm-service-broker.rhcc.svc:8005

